# Generated by Django 4.0.8 on 2024-11-28 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencia',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.tercero'),
        ),
    ]
