# Generated by Django 4.0.8 on 2024-11-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_alter_tercero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='specs'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='certificado_laboral',
            field=models.FileField(blank=True, null=True, upload_to='specs'),
        ),
    ]
