# Generated by Django 4.0.8 on 2024-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_alter_tercero_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='identificacion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='certificado_laboral',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
