# Generated by Django 4.0.8 on 2024-11-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.estadocontrato'),
        ),
    ]
