# Generated by Django 4.0.8 on 2024-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='contratos'),
        ),
    ]
